# Generated by Django 4.2.6 on 2023-12-30 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waste_reduction_buddy', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Created_By',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
