# Generated by Django 4.2.6 on 2023-12-30 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waste_reduction_buddy', '0003_appointment_created_by_alter_appointment_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Created_By',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
