# Generated by Django 4.2.6 on 2024-01-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_reduction_buddy', '0004_alter_appointment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Appointed_To',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
