# Generated by Django 4.2.6 on 2024-01-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste_reduction_buddy', '0005_appointment_appointed_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Appointed_To',
        ),
    ]
