# Generated by Django 4.2.6 on 2024-01-29 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste_reduction_buddy', '0006_remove_appointment_appointed_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='selected_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waste_reduction_buddy.record'),
        ),
    ]
