# Generated by Django 4.2.6 on 2024-02-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_reduction_buddy', '0009_alter_compost_inquiry_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='state',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='appointment',
            name='full_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='selling_option',
            field=models.CharField(blank=True, choices=[('sell', 'Sell'), ('donate', 'Donate')], max_length=10, null=True),
        ),
    ]
