# Generated by Django 4.2.6 on 2024-02-26 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_reduction_buddy', '0013_blogpost_alter_appointment_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='city',
        ),
        migrations.AddField(
            model_name='appointment',
            name='calendar',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
