# Generated by Django 4.2.6 on 2024-02-26 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_reduction_buddy', '0014_remove_appointment_city_appointment_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
