# Generated by Django 5.0.2 on 2024-03-10 14:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_reduction_buddy', '0016_alter_appointment_calendar_alter_appointment_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='calendar',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
