# Generated by Django 5.0.2 on 2024-03-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_reduction_buddy', '0018_rename_zipcode_record_nin_remove_record_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='nin',
            field=models.CharField(max_length=20),
        ),
    ]
