# Generated by Django 5.0.2 on 2024-03-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_reduction_buddy', '0020_alter_record_options_alter_record_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.CharField(max_length=150),
        ),
    ]
