# Generated by Django 5.0.2 on 2024-03-11 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_reduction_buddy', '0021_alter_record_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(14, 1, 0, 544118)),
        ),
    ]
