# Generated by Django 5.0.2 on 2024-03-25 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_reduction_buddy', '0029_remove_record_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='phone',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(14, 34, 45, 705371)),
        ),
        migrations.AlterField(
            model_name='compost_inquiry',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
