# Generated by Django 5.0.2 on 2024-03-25 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_reduction_buddy', '0030_remove_contact_us_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(14, 40, 22, 772730)),
        ),
        migrations.AlterField(
            model_name='compost_inquiry',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
